spring:
  application:
    name: hub-service
  config:
    import: configserver:http://localhost:18080
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  jpa:
    properties:
      hibernate:
        default_schema: HUB_SCHEMA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
