spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service  # 애플리케이션 이름을 ‘gateway-service’로 설정

  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: order-service  # 라우트 식별자
          uri: lb://order-service  # ‘order-service’라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/orders/**, /order-service/v3/api-docs
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/hubs/**, /api/routes/**, /hub-service/v3/api-docs
        - id: product-service  # 라우트 식별자
          uri: lb://product-service  # ‘product-service’라는 이름으로 로드 밸런싱된 서비스로 라우팅
          predicates:
            - Path=/api/products/**, /product-service/v3/api-docs
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/companies/**, /company-service/v3/api-docs
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /user-service/v3/api-docs
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /auth-service/v3/api-docs
        - id: delivery-manager-service
          uri: lb://delivery-manager-service
          predicates:
            - Path=/api/managers/**, /delivery-manager-service/v3/api-docs
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/deliveries/**, /delivery-service/v3/api-docs
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /message-service/v3/api-docs

      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#
#  config:
#    import: configserver:http://localhost:18080

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  swagger-ui:
    urls[0]:
      name: order-service
      url: /order-service/v3/api-docs
    urls[1]:
      name: hub-service
      url: /hub-service/v3/api-docs
    urls[2]:
      name: product-service
      url: /product-service/v3/api-docs
    urls[3]:
      name: company-service
      url: /company-service/v3/api-docs
    urls[4]:
      name: user-service
      url: /user-service/v3/api-docs
    urls[5]:
      name: auth-service
      url: /auth-service/v3/api-docs
    urls[6]:
      name: delivery-manager-service
      url: /delivery-manager-service/v3/api-docs
    urls[7]:
      name: delivery-service
      url: /delivery-service/v3/api-docs
    urls[8]:
      name: message-service
      url: /message-service/v3/api-docs
    use-root-path: true

auth:
  url: "http://localhost:18081/api/auth"
